// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsFYvzBpDO27TxcPGp3M60Svf_tO0J2Vk',
    appId: '1:773294780857:web:29fc2447bf512c2f3f8668',
    messagingSenderId: '773294780857',
    projectId: 'flutter-notifications-334f9',
    authDomain: 'flutter-notifications-334f9.firebaseapp.com',
    storageBucket: 'flutter-notifications-334f9.appspot.com',
    measurementId: 'G-R9TSYRGSKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjSPUYmXNrHRdS0GTGoBzFIgMQ8LI4gpI',
    appId: '1:773294780857:android:1a67eb122c23b3853f8668',
    messagingSenderId: '773294780857',
    projectId: 'flutter-notifications-334f9',
    storageBucket: 'flutter-notifications-334f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvUg8vVp9B9qvw_FpHNdrJLW-t9jb8lks',
    appId: '1:773294780857:ios:a99a43bfabee0b513f8668',
    messagingSenderId: '773294780857',
    projectId: 'flutter-notifications-334f9',
    storageBucket: 'flutter-notifications-334f9.appspot.com',
    iosBundleId: 'com.example.flutterNotifications',
  );
}
